=== DanielSinclair/bpp/keys.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://plasmo.com/bpp/keys.schema.json",
  "title": "Browser Platform Publisher keys",
  "description": "Keys for the Browser Platform Publisher.",
  "$ref": "#/definitions/Root",
  "definitions": {
    "Root": {
      "type": "object",
      "properties": {
        "chrome": {
          "$ref": "#/definitions/Chrome"
        },
        "firefox": {
          "$ref": "#/definitions/Firefox"
        },
        "opera": {
          "$ref": "#/definitions/Opera"
        },
        "edge": {
          "$ref": "#/definitions/Edge"
        },
        "safari": {
          "$ref": "#/definitions/Safari"
        }
      }
    },
    "Chrome": {
      "description": "For refreshToken and clientId, follow: https://github.com/PlasmoHQ/chrome-webstore-api/blob/main/token.md",
      "type": "object",
      "properties": {
        "extId": {
          "type": "string",
          "description": "Get it from https://chrome.google.com/webstore/detail/EXT_ID"
        },
        "refreshToken": {
          "type": "string",
          "description": "See: https://github.com/PlasmoHQ/chrome-webstore-api/blob/main/token.md"
        },
        "clientId": {
          "type": "string",
          "description": "See: https://github.com/PlasmoHQ/chrome-webstore-api/blob/main/token.md"
        },
        "zip": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "description": "The target audience to publish to. Defaults to 'default'",
          "enum": ["default", "trustedTesters"],
          "default": "default"
        }
      },
      "required": ["extId", "refreshToken", "clientId"]
    },
    "Firefox": {
      "type": "object",
      "description": "For API Key and API Secret, visit: https://addons.mozilla.org/en-US/developers/addon/api/key/",
      "properties": {
        "apiKey": {
          "type": "string",
          "description": "The JWT issuer, from https://addons.mozilla.org/en-US/developers/addon/api/key/"
        },
        "apiSecret": {
          "type": "string",
          "description": "The JWT secret, from https://addons.mozilla.org/en-US/developers/addon/api/key/"
        },
        "extId": {
          "type": "string",
          "description": "This is the extension UUID, get it from https://addons.mozilla.org/en-US/developers/addon/{ext-name}/edit, under Technical Details. If it is embedded in your manifest under gecko.id, omit this property."
        },
        "zip": {
          "type": "string"
        }
      },
      "required": ["apiKey", "apiSecret"]
    },
    "Edge": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "Create an Edge add-on and get it from the dashboard: https://partner.microsoft.com/en-us/dashboard/microsoftedge/{product-id}/package/dashboard"
        },
        "clientId": {
          "type": "string",
          "description": "You can find your client ID by visiting the Microsoft Partner Center:  https://partner.microsoft.com/en-us/dashboard/microsoftedge/publishapi"
        },
        "clientSecret": {
          "type": "string",
          "description": "You can find your client secret by visiting the Microsoft Partner Center:  https://partner.microsoft.com/en-us/dashboard/microsoftedge/publishapi"
        },
        "accessTokenUrl": {
          "type": "string",
          "description": "You can find your access token URL by visiting the Microsoft Partner Center:  https://partner.microsoft.com/en-us/dashboard/microsoftedge/publishapi"
        },
        "zip": {
          "type": "string"
        },
        "notes": {
          "type": "string",
          "description": "Provide notes for certification to the Edge Add-ons reviewers"
        }
      },
      "required": ["productId", "clientId", "clientSecret", "accessTokenUrl"]
    },
    "Opera": {
      "type": "object",
      "description": "NOTE: Opera add-ons reviewer require inspecting your extension's source code.",
      "properties": {
        "packageId": {
          "type": "string",
          "description": "Get it from https://addons.opera.com/developer/package/PACKAGE_ID"
        },
        "sessionid": {
          "type": "string",
          "description": "npx web-ext-deploy --get-cookies=opera"
        },
        "csrftoken": {
          "type": "string",
          "description": "npx web-ext-deploy --get-cookies=opera"
        },
        "zip": {
          "type": "string"
        },
        "changelog": {
          "type": "string",
          "description": "Provide changelog for the Opera users"
        }
      },
      "required": ["packageId", "csrftoken", "sessionid"]
    },
    "Safari": {
      "type": "object",
      "properties": {
        "zip": {
          "type": "string"
        },
        "bundleId": {
          "type": "string",
          "description": "i.e. com.plasmo.mock"
        },
        "extensionBundleId": {
          "type": "string",
          "description": "i.e. com.plasmo.mock.extension"
        },
        "appName": {
          "type": "string",
          "description": "i.e. Plasmo Mock"
        },
        "appCategory": {
          "type": "string",
          "description": "last component of LSApplicationCategoryType (i.e. business)"
        },
        "platforms": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "defaults to iOS and macOS"
        },
        "buildNumber": {
          "type": "number",
          "description": "defaults to GITHUB_RUN_NUMBER"
        },
        "appleId": {
          "type": "string",
          "description": "Your Apple email address"
        },
        "appleDevPortalId": {
          "type": "string",
          "description": "Apple Developer Account email address"
        },
        "teamName": {
          "type": "string",
          "description": "i.e. Plasmo Corp."
        },
        "teamId": {
          "type": "string",
          "description": "i.e. Q2CBPJ58CA"
        },
        "itunesConnectId": {
          "type": "string",
          "description": "App Store Connect Account email address"
        },
        "itcTeamName": {
          "type": "string",
          "description": "i.e. \"Company Name\" for Apple IDs in multiple teams"
        },
        "itcTeamId": {
          "type": "string",
          "description": "i.e. \"18742801\" for Apple IDs in multiple teams"
        },
        "provisioningProfiles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "bundleId": { "type": "string" },
              "platform": { "enum": ["ios", "macos"] },
              "type": { "enum": ["appstore", "adhoc", "development", "enterprise", "developer_id", "mac_installer_distribution"] },
              "name": { "type": "string" }
            }
          },
          "description": "array of ProvisioningProfiles"
        },
        "keyId": {
          "type": "string",
          "description": "i.e. \"D383SF739\""
        },
        "key": {
          "type": "string",
          "description": "i.e. \"-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHknlhdlYdLu\n-----END PRIVATE KEY-----\""
        },
        "issuerId": {
          "type": "string",
          "description": "i.e. \"6053b7fe-68a8-4acb-89be-165aa6465141\""
        },
        "duration": {
          "type": "number",
          "description": "optional (maximum 1200)"
        },
        "matchPassword": {
          "type": "string",
          "description": "shared storage encryption password"
        },
        "matchStorageMode": {
          "type": "string",
          "description": "defaults to git"
        },
        "matchGitUrl": {
          "type": "string",
          "description": "for git"
        },
        "matchGitBranch": {
          "type": "string",
          "description": "for git"
        },
        "matchGitBasicAuthorization": {
          "type": "string",
          "description": "for git"
        },
        "matchGitBearerAuthorization": {
          "type": "string",
          "description": "for git"
        },
        "matchGitPrivateKey": {
          "type": "string",
          "description": "for git"
        },
        "matchGoogleCloudBucketName": {
          "type": "string",
          "description": "for Google Cloud"
        },
        "matchGoogleCloudKeysFile": {
          "type": "string",
          "description": "for Google Cloud"
        },
        "matchGoogleCloudProjectId": {
          "type": "string",
          "description": "for Google Cloud"
        },
        "matchS3Region": {
          "type": "string",
          "description": "for S3"
        },
        "matchS3AccessKey": {
          "type": "string",
          "description": "for S3"
        },
        "matchS3SecretAccessKey": {
          "type": "string",
          "description": "for S3"
        },
        "matchS3Bucket": {
          "type": "string",
          "description": "for S3"
        },
        "workspace": {
          "type": "string",
          "description": "non-tmp static directory to generate workspace to (for file system debugging or project exports)"
        },
        "verbose": {
          "type": "boolean",
          "description": "toggle more detailed logs"
        }
      },
      "required": ["bundleId", "appName", "appCategory", "keyId", "key", "issuerId"]
    }
  }
}

=== DanielSinclair/bpp/keys.template.json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/v2/keys.schema.json",
  "chrome": {
    "clientId": "123",
    "refreshToken": "789",
    "extId": "abcd"
  },
  "firefox": {
    "extId": "aaaaaaa-aaaa-bbbb-cccc-dddddddddddd",
    "apiKey": "abcd",
    "apiSecret": "efgh"
  },
  "edge": {
    "clientId": "aaaaaaa-aaaa-bbbb-cccc-dddddddddddd",
    "clientSecret": "abcdefg",
    "productId": "aaaaaaa-aaaa-bbbb-cccc-dddddddddddd",
    "accessTokenUrl": "https://login.microsoftonline.com/aaaaaaa-aaaa-bbbb-cccc-dddddddddddd/oauth2/v2.0/token"
  },
  "opera": {
    "packageId": "123",
    "csrftoken": "abcd",
    "sessionid": "abcd"
  },
  "safari": {
    "bundleId": "com.plasmo.mock",
    "appName": "Plasmo Mock",
    "appCategory": "developer-tools",
    "appleId": "DEVELOPER_APPLE_ID",
    "teamId": "APPLE_DEVELOPER_TEAM_ID",
    "teamName": "Plasmo Corp.",
    "keyId": "APP_STORE_CONNECT_API_KEY_ID",
    "issuerId": "APP_STORE_CONNECT_API_ISSUER_ID",
    "key": "APP_STORE_CONNECT_API_KEY",
    "matchPassword": "YOUR_MATCH_ENCRYPTION_PASSWORD",
    "matchGitUrl": "YOUR_MATCH_REPO"
  }
}
